### ISSUE TITLE
Setting API Key

### ISSUE THREAD

**Issue by oleteacher** [sourcezax/Ephpai#1]
I know this will be a stupid question, but where do you define your openai key? 

I see `private $apikey;` so use this like:

```
<?php
header("Content-type: image/jpeg");
$apikey = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
require "../Ephpai.php";
$Requestgpt=new Ephpai('blue cat');
$Requestgpt->generateImage(true);//
if((!$Requestgpt->setImgsize('1024x1024'))||(!$Requestgpt->executeQuery()))
     die ($Requestgpt->error());
else
{
    if (!$Requestgpt->displayImg(0,100))
    die ($Requestgpt->error());
}
?>
```
This is what displayed:

![image](https://user-images.githubusercontent.com/26278259/224187364-7b722a17-1b4a-46e9-9947-758c5ec64068.png)

Please help this old woman understand:)

**Comment by sourcezax** [comment]
Hello Suzan,

Thank you for your message, and I hope that this library will be useful to
you.

I haven't detailed enough documentation about the key, i'm sorry.

I will upgrade documentation soon.


To enter the openai apikey, you have two possibilities :

-Setting an environnement variable, as asked by openai recommandations. You
need to create this environnement variable on your server.
I personnaly don't use this, but i followed their recommandations. You can
set it on php too by using the putenv php function at the beginning of your
script :

$apikey="youropenaikey"
putenv("OAIPIKEY=$apikey"); 

(Edit : mistake in my precedent message)

-You can use the public method setApikey() of the ephpai class too, who do
the same thing and easy to use.
Here is an example
<?php
header("Content-type: image/jpeg");
require "../Ephpai.php";
$apikey = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
$Requestgpt=new Ephpai('blue cat');

//HERE : we set the api key
$Requestgpt->setApikey($apikey);

$Requestgpt->generateImage(true);

if((!$Requestgpt->setImgsize('1024x1024'))||(!$Requestgpt->executeQuery()))
     die("Oups");
else
{
$imgdata=$Requestgpt->getTextresult(0);
$image = @imagecreatefromstring($imgdata);
imagejpeg($image,null, 75);
}
?>

Hoping to have been useful to you,
Best regards,
Thomas Missonier

**Comment by oleteacher** [comment]
Thank you much for reply and taking time to explain. It now works for me using:

```
<?php
header("Content-type: image/jpeg");
require "../Ephpai.php";
$apikey = "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
$Requestgpt=new Ephpai('blue cat');

//HERE : we set the api key
$Requestgpt->setApikey($apikey);

$Requestgpt->generateImage(true);

if((!$Requestgpt->setImgsize('1024x1024'))||(!$Requestgpt->executeQuery()))
     die("Oups");
else
{
$imgdata=$Requestgpt->getTextresult(0);
$image = @imagecreatefromstring($imgdata);
imagejpeg($image,null, 75);
}
?>
```
